### ISSUE TITLE
MAX button doesn't reflect the correct amount from Wallet

### ISSUE THREAD

**Issue by 8d526** [polkaswitch/polkaswitch-ui#11]
On Polyscan my USDC balance shows 0.012096 which is correct

But on the app it shows me balance of 0.0121 and when i click MAX it gives me insufficient funds. The app should display the correct balance 0.012096, so when i click MAX i doesnt give me the insufficient balance msg. 

Many of us would just want to do MAX, so if doesnt work then going to the explorer to check the balance then typing in the balance is time consuming

**Comment by chillvybz** [comment]
Closed - fixed with this for now:
https://github.com/polkaswitch/polkaswitch-ui/commit/bd1b832001965db182478f0a5cf3f93e29492d0c#diff-3533e55aa675c5c5529fc2b3f3cc9ad898061a44193c121926e07158e18efe2dR102
