### ISSUE TITLE
Allow for custom Gas Price input setting

### ISSUE THREAD

**Issue by chillvybz** [polkaswitch/polkaswitch-ui#13]
![image](https://user-images.githubusercontent.com/85249140/123563808-beb32b00-d784-11eb-986a-a0beaba32419.png)

Right now we only offer 3 static options for Gas Price (Auto, Fast, Fastest).
Users sometimes want to be able input a custom price when the difference between options is too large for users.

Similar UX to Slip Tolerance.

**Comment by davidkoller318** [comment]
Okay
