### ISSUE TITLE
Display an Intermediary "Approve" Button before "Swap" Button

### ISSUE THREAD

**Issue by chillvybz** [polkaswitch/polkaswitch-ui#14]
![image](https://user-images.githubusercontent.com/85249140/123563885-27020c80-d785-11eb-86d4-2291ee8bcd07.png)

**Context** 

At the moment, if a user is swapping for the first time using our platform, we call the APPROVE() contract function to approve the spending amount required to perform the swap. We approve a relatively large amount so that we don't need to do repeat approvals in the future.

However for new users, this appears as two transactions that need to be signed/approved via Metamask.

**Solution**

We should add an intermediary Approve button when some token is "spending" first time. Because at the moment we see only swap and somebody won`t be understand why he or she need to sign two transactions instead of one for usual swapping

You can see the current logic here:
https://github.com/polkaswitch/polkaswitch-ui/blob/main/src/client/js/utils/swapFn.js#L166-L171

where we call `getAllowance()` and depending on if the `getAllowance()` is >= the swap amount, we either call `Approve()` or `Swap()`.

If we need to call `Approve()`, please render the "APPROVE" red button instead of "SWAP" red button.
Once the `Approve()` func call is cleared in Metamask, then show the "SWAP" red button.

**Comment by davidkoller318** [comment]
Okay

**Comment by renchuqiao** [comment]
@davidkoller318 This is to add a separate approve button if we never approve this token for this address before.

**Comment by 8d526** [comment]
This is to add the approve button if for this particular token we need to get approval from msg.sender.

**Comment by davidkoller318** [comment]
@8d526 
Currently we are using uniswapv2 when swap?

**Comment by chillvybz** [comment]
I am un-assigning this from David for now.
The other ones are higher priority.

**Comment by davidkoller318** [comment]
Hi, @chillvybz . 
I 'm working on this task for now.
