### ISSUE TITLE
Show Balances for every coin in the Token Search

### ISSUE THREAD

**Issue by chillvybz** [polkaswitch/polkaswitch-ui#15]
![image](https://user-images.githubusercontent.com/85249140/123564070-ec4ca400-d785-11eb-86c1-796ec4811fc8.png)

It would be convenient for users to be able to list their coin balancers per coin in the Token Search list.

**Comment by davidkoller318** [comment]
Okay.

**Comment by davidkoller318** [comment]
Hi, @8d526 . I have a quick question. 
Could you explain about above issue in detail?
We should display coin balance of user account (Meta-mask)?
ex:) If I have 3 DAI on my meta mask, it should be displayed when search DAI token?

**Comment by renchuqiao** [comment]
Yup. If user connects to our site with Metamask, we will display the token balance in the token list from Metamask. We also support walletConnect now. So we will just fetch balance from whatever the wallet that is connecting to our site. 

![image](https://user-images.githubusercontent.com/6487514/125850492-e62d7175-75eb-4887-bb82-daab42ed07cc.png)

**Comment by 8d526** [comment]
Yup. If user connects to our site with Metamask, we will display the token balance in the token list from Metamask. We also support walletConnect now. So we will just fetch balance from whatever the wallet that is connecting to our site. Something like this below
![image](https://user-images.githubusercontent.com/69666954/125855433-3616b684-6f03-4b11-bb7e-8b4f25173bcf.png)
