### ISSUE TITLE
Transaction History: Pending Tx need to poll every 10 seconds for updates

### ISSUE THREAD

**Issue by chillvybz** [polkaswitch/polkaswitch-ui#23]
**Problem**

![image](https://user-images.githubusercontent.com/85249140/127253642-ee99f733-2bd4-47b4-81d0-3d5e2cec3a1a.png)

When you submit a transaction and while it's still PENDING, if you refresh the browser, we lose real-time event updates when the TX actually completes.

It will stay stuck in the PENDING state (see screenshot above).

**Solution**

When the browser refreshes, and we re-load the TX history from the Browser state, we should query for updates (via 10 seconds polling) for any PENDING TX with the blockchain to get any updates if the TX completed or failed. 

If they are completed or failed, no need to fetch updates.

**Comment by davidkoller318** [comment]
Okay. got it.
