### ISSUE TITLE
Advanced Settings Incorrectly Loading on Refresh

### ISSUE THREAD

**Issue by kirushanths** [polkaswitch/polkaswitch-ui#25]
Two similiar bugs introduced with this merge: #20 

**First:**

<img width="438" alt="Screen Shot 2021-07-30 at 3 18 17 PM" src="https://user-images.githubusercontent.com/1319454/127701790-95846b77-624b-42e5-9a4a-c9fc56eb1969.png">

Reproduction Steps:
1) Load app for first time
2) Go to advanced settings
3) Note how the gas-price custom box **incorrectly** shows "-1", it should be blank.

**Second:**

<img width="463" alt="Screen Shot 2021-07-30 at 3 20 47 PM" src="https://user-images.githubusercontent.com/1319454/127701926-cdc4078b-d449-413c-acb8-bb954d26e76b.png">

Reproduction Steps:
1) Load app and go to advanced settings
2) change slip tolerance to any custom number (i.e 23)
3) Refresh the app and go back to advanced settings
3) Note how the slip tolerance custom box correctly shows "23", but it also **incorrectly** highlights the default "0.5%".

**Comment by davidkoller318** [comment]
Okay. I will check it.

**Comment by davidkoller318** [comment]
Hi, @kirushanths 
I fixed it. and created new PR
