### ISSUE TITLE
Balances in Token Search Dropdown are not auto-updating after a Successful Swap

### ISSUE THREAD

**Issue by chillvybz** [polkaswitch/polkaswitch-ui#27]
![image](https://user-images.githubusercontent.com/85249140/128091791-1a0b006b-2a73-49f9-b4b6-99458e76909b.png)
![image](https://user-images.githubusercontent.com/85249140/128091798-9c27de4e-ddc3-424b-b79f-cc93d7694e67.png)

When you successfully make a trade and try to view your balance in the Token Search dropdown, it is showing the old balance.
I expect the balances to update there as well.

**Comment by davidkoller318** [comment]
Okay, I will check it and fix the issue.
