### ISSUE TITLE
Swing: New Navbar Layout

### ISSUE THREAD

**Issue by chillvybz** [polkaswitch/polkaswitch-ui#42]
### **New Navbar Layout:**
![image](https://user-images.githubusercontent.com/85249140/132242948-20fc9d84-84f4-4106-bc92-6cc5f43001b3.png)

### **Disconnected Wallet State:**
![image](https://user-images.githubusercontent.com/85249140/132243186-0b9ba98b-820c-4d31-832a-7a4bc1a716fb.png)

### **Account Dropdown:**
![image](https://user-images.githubusercontent.com/85249140/132243075-5cd0b9e6-0dac-4ec2-aa9d-73306ad3fa3f.png)

Notes:
- Don't show the balances for now, we will add that later

### **Settings Dropdown:**
![image](https://user-images.githubusercontent.com/85249140/132242932-d7c40691-608f-40a8-b08c-96b655f94d53.png)

### **Transactions Dropdown:**
![image](https://user-images.githubusercontent.com/85249140/132243104-c8e33cce-9ce4-4a96-9afa-faaf687412c5.png)
(Please ignore the pagination for now, only show the last 5 TXes)

### **Mobile:**
![image](https://user-images.githubusercontent.com/85249140/132242996-7a4c5c03-a6c1-486f-a4d7-0f637b545b62.png)

Please ignore the Markets and Share Tabs for now.

**Comment by chillvybz** [comment]
Ignore the DARK MODE colors for now.
I have to build a better DARK MODE CSS classes

**Comment by davidkoller318** [comment]
@chillvybz . 
Okay. I got it.
