### ISSUE TITLE
App crashes if too many decimals are entered

### ISSUE THREAD

**Issue by SirFrancisDrake** [polkaswitch/polkaswitch-ui#7]
**Steps to reproduce**:
In the "*You pay*" input, enter a number with 19 digits after the decimal point

**Expected behaviour**:
Some kind of input validation kicks in and catches the input.

**Actual behaviour**:
App crashes (renders a clean page) with the following console error:
```
Uncaught (in promise) Error: fractional component exceeds decimals (fault="underflow", 
operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.1.0)
```

**Comment by chillvybz** [comment]
Fixed with https://github.com/polkaswitch/polkaswitch-ui/commit/bd657995e308743ab7da581f9111f2e4100ad735
