### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by 8d526** [polkaswitch/polkaswitch-ui#8]
Support dark mode and dark color scheme.

**Comment by chillvybz** [comment]
Please see Dark Mode Theme.

![image](https://user-images.githubusercontent.com/85249140/133661917-5af5ec19-dc0b-48cd-a354-763afb8336e2.png)
![image](https://user-images.githubusercontent.com/85249140/133661971-8f0c13da-f9c2-4b8d-9db6-600d0e684323.png)
![image](https://user-images.githubusercontent.com/85249140/133661984-d6436fc0-6a0c-47e1-8e44-48f912851a39.png)
![image](https://user-images.githubusercontent.com/85249140/133661998-d47b6d17-da2e-4b07-b567-4d3a92b8cecb.png)

Only apply the basic COLORS.
Please ignore margin/padding/rounded-corners/sizing.
**ONLY FOCUS ON COLORS.**

This update should build a foundation for theme-support in general in our app.
**So we have to be smart about our CSS class structure and hierarchy and overrides.**

**Comment by chillvybz** [comment]
Please add a DARK MODE Toggle button in the Navbar beside the Bridge Button:
![image](https://user-images.githubusercontent.com/85249140/133665312-da2df23f-39b6-4f4b-92b3-edc81aff0966.png)

On the left of the Bridge Button
![image](https://user-images.githubusercontent.com/85249140/133665330-74238451-2755-41f1-a418-0f95d12f985f.png)
