### ISSUE TITLE
Transaction History is not preserved on Browser Refresh

### ISSUE THREAD

**Issue by 8d526** [polkaswitch/polkaswitch-ui#9]
Transaction history box goes empty after you refresh the screen.

When you submit a transaction, the TX History modal populates:
![image](https://user-images.githubusercontent.com/85249140/123850084-95f77680-d8e7-11eb-9a3b-c97035430a46.png)

![image](https://user-images.githubusercontent.com/85249140/123849997-74968a80-d8e7-11eb-963c-b75ab696905b.png)

After you refresh the page, the history disappears and reverts back to clean stateP
![image](https://user-images.githubusercontent.com/85249140/123849962-6c3e4f80-d8e7-11eb-86b5-61ffca3fb9b4.png)

**Comment by kirushanths** [comment]
Potential Solutions:
- Using LocalStorage (already `store` npm package added)
- Serialize/De-serialize the TX History

Extra Points:
- Fetching the history of swaps right from the chain

**Comment by chillvybz** [comment]
Fixed with #17
